In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import opendatasets as od
import os

pd.set_option('display.max_rows', 300)

In [2]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')
train_labels = pd.read_csv('data/train_labels.csv')
submission = pd.read_csv('data/sample_submission.csv')

In [4]:
train.drop(columns=['fullscreen', 'hq', 'music', 'page'], inplace=True)
train

,session_id,index,elapsed_time,event_name,name,level,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0-4
1,20090312431273200,1,1323,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
2,20090312431273200,2,831,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
3,20090312431273200,3,1147,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
4,20090312431273200,4,1863,person_click,basic,0,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296941,22100221145014656,1600,5483231,navigate_click,undefined,22,343.887291,36.701026,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,13-22
26296942,22100221145014656,1601,5485166,navigate_click,undefined,22,332.696070,141.493178,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22
26296943,22100221145014656,1602,5485917,navigate_click,undefined,22,369.912859,140.569205,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,13-22
26296944,22100221145014656,1603,5486753,navigate_click,undefined,22,252.299653,123.805889,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22
26296945,22100221145014656,1604,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22

In [5]:
train.head()

,session_id,index,elapsed_time,event_name,name,level,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0-4
1,20090312431273200,1,1323,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
2,20090312431273200,2,831,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
3,20090312431273200,3,1147,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
4,20090312431273200,4,1863,person_click,basic,0,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4

Each columns null percentage

In [30]:
train.isnull().sum()/len(train)*100

session_id         0.000000
index              0.000000
elapsed_time       0.000000
event_name         0.000000
name               0.000000
level              0.000000
room_coor_x        7.884079
room_coor_y        7.884079
screen_coor_x      7.884079
screen_coor_y      7.884079
hover_duration    92.386021
text              63.428685
fqid              31.465308
room_fqid          0.000000
text_fqid         63.428286
level_group        0.000000
dtype: float64

# Process session_id #1

In [6]:
sess1 = train[train['session_id']==20090312431273200]
sess1

,session_id,index,elapsed_time,event_name,name,level,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0-4
1,20090312431273200,1,1323,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
2,20090312431273200,2,831,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
3,20090312431273200,3,1147,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
4,20090312431273200,4,1863,person_click,basic,0,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,20090312431273200,927,1267357,navigate_click,undefined,22,927.307255,-10.355929,838.0,335.0,NaN,NaN,tomap,tunic.historicalsociety.entry,NaN,13-22
877,20090312431273200,928,1268292,map_hover,basic,22,NaN,NaN,NaN,NaN,366.0,NaN,tomap,tunic.historicalsociety.entry,NaN,13-22
878,20090312431273200,929,1269474,map_click,undefined,22,457.523005,22.141338,443.0,316.0,NaN,NaN,tunic.capitol_2,tunic.historicalsociety.entry,NaN,13-22
879,20090312431273200,930,1270708,navigate_click,undefined,22,224.190321,-60.268671,404.0,337.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22
880,20090312431273200,931,1272679,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22

In [7]:
train_labels

                   session_id  correct
0        20090312431273200_q1        1
1        20090312433251036_q1        0
2        20090312455206810_q1        1
3        20090313091715820_q1        0
4        20090313571836404_q1        1
...                       ...      ...
424111  22100215342220508_q18        1
424112  22100215460321130_q18        1
424113  22100217104993650_q18        1
424114  22100219442786200_q18        1
424115  22100221145014656_q18        1

[424116 rows x 2 columns]

In [8]:
# train_labels are ordered by question 1 to 18, not by session_id and question number
train_labels.sort_values('session_id')

                   session_id  correct
0        20090312431273200_q1        1
212058  20090312431273200_q10        1
235620  20090312431273200_q11        1
259182  20090312431273200_q12        1
282744  20090312431273200_q13        0
...                       ...      ...
117809   22100221145014656_q5        0
141371   22100221145014656_q6        0
164933   22100221145014656_q7        0
188495   22100221145014656_q8        0
212057   22100221145014656_q9        1

[424116 rows x 2 columns]

Split train_labels id and questions

In [9]:
train_labels_split = train_labels.copy()
train_labels_split[['id', 'question']] = train_labels_split['session_id'].str.split('_q', expand=True)
train_labels_split = train_labels_split[['session_id', 'id', 'question', 'correct']]
train_labels_split['question'] = train_labels_split['question'].astype('int')
train_labels_split.sort_values(['id', 'question'],inplace=True)
train_labels_split.reset_index(drop=True, inplace=True)
train_labels_split

                   session_id                 id  question  correct
0        20090312431273200_q1  20090312431273200         1        1
1        20090312431273200_q2  20090312431273200         2        1
2        20090312431273200_q3  20090312431273200         3        1
3        20090312431273200_q4  20090312431273200         4        1
4        20090312431273200_q5  20090312431273200         5        1
...                       ...                ...       ...      ...
424111  22100221145014656_q14  22100221145014656        14        0
424112  22100221145014656_q15  22100221145014656        15        0
424113  22100221145014656_q16  22100221145014656        16        0
424114  22100221145014656_q17  22100221145014656        17        1
424115  22100221145014656_q18  22100221145014656        18        1

[424116 rows x 4 columns]

In [10]:
train_labels_split.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424116 entries, 0 to 424115
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   session_id  424116 non-null  object
 1   id          424116 non-null  object
 2   question    424116 non-null  int32
 3   correct     424116 non-null  int64
dtypes: int32(1), int64(1), object(2)
memory usage: 11.3+ MB

In [11]:
train_labels.loc[train_labels['session_id'] == '20090312431273200_q1', 'correct']

0    1
Name: correct, dtype: int64

In [12]:
sess1_list = []
for i in range(1, 18):
    print(train_labels.loc[train_labels['session_id']
          == '20090312431273200_q{}'.format(i), 'correct'])
    sess1_list.append(
        train_labels.loc[train_labels['session_id'] == '20090312431273200_q{}'.format(i), 'correct'])
# print(train_labels[train_labels['session_id']=='20090312431273200_q1'])

0    1
Name: correct, dtype: int64
23562    1
Name: correct, dtype: int64
47124    1
Name: correct, dtype: int64
70686    1
Name: correct, dtype: int64
94248    1
Name: correct, dtype: int64
117810    1
Name: correct, dtype: int64
141372    1
Name: correct, dtype: int64
164934    1
Name: correct, dtype: int64
188496    1
Name: correct, dtype: int64
212058    1
Name: correct, dtype: int64
235620    1
Name: correct, dtype: int64
259182    1
Name: correct, dtype: int64
282744    0
Name: correct, dtype: int64
306306    1
Name: correct, dtype: int64
329868    1
Name: correct, dtype: int64
353430    0
Name: correct, dtype: int64
376992    1
Name: correct, dtype: int64

### train_labels_split - processed labels
- sess1 - session #1

In [13]:
sess1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 881 entries, 0 to 880
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      881 non-null    int64
 1   index           881 non-null    int64
 2   elapsed_time    881 non-null    int64
 3   event_name      881 non-null    object
 4   name            881 non-null    object
 5   level           881 non-null    int64
 6   room_coor_x     813 non-null    float64
 7   room_coor_y     813 non-null    float64
 8   screen_coor_x   813 non-null    float64
 9   screen_coor_y   813 non-null    float64
 10  hover_duration  65 non-null     float64
 11  text            384 non-null    object
 12  fqid            652 non-null    object
 13  room_fqid       881 non-null    object
 14  text_fqid       384 non-null    object
 15  level_group     881 non-null    object
dtypes: float64(5), int64(4), object(7)
memory usage: 117.0+ KB

In [14]:
sess1.fqid.value_counts()

worker                            64
archivist                         46
gramps                            44
crane_ranger                      32
wells                             32
toentry                           23
confrontation                     22
flag_girl                         20
groupconvo                        18
boss                              17
tomap                             16
teddy                             14
seescratches                      13
tobasement                        11
groupconvo_flag                   11
archivist_glasses                 10
tostacks                          10
expert                             9
cs                                 9
savedteddy                         8
ch3start                           8
tunic.capitol_1                    7
logbook                            7
tunic.historicalsociety            7
glasses                            7
trigger_scarf                      6
tofrontdesk                        6
tunic.drycleaner                   6
businesscards                      5
tunic.library                      5
reader                             5
journals                           5
what_happened                      5
directory                          5
colorbook                          5
reader_flag                        5
tracks                             4
journals.hub.topics                4
directory.closeup.archivist        4
businesscards.card_0.next          4
tunic.capitol_2                    4
janitor                            4
tunic                              4
unlockdoor                         4
logbook.page.bingo                 4
trigger_coffee                     3
journals_flag.pic_0.bingo          3
journals.pic_0.next                3
reader.paper0.next                 3
chap2_finale_c                     3
tunic.kohlcenter                   3
plaque                             3
tracks.hub.deer                    3
remove_cup                         2
reader_flag.paper0.next            2
key                                2
journals_flag                      2
journals_flag.hub.topics           2
coffee                             2
tunic.flaghouse                    2
tocage                             2
reader_flag.paper2.bingo           2
chap4_finale_c                     2
journals.pic_2.bingo               2
businesscards.card_bingo.next      2
plaque.face.date                   2
togrampa                           2
report                             2
retirement_letter                  2
magnify                            2
notebook                           2
outtolunch                         2
businesscards.card_1.next          2
photo                              2
businesscards.card_bingo.bingo     2
tohallway                          2
tomicrofiche                       2
reader.paper2.bingo                2
wellsbadge                         2
tunic.hub.slip                     2
journals_flag.hub.topics_old       1
journals_flag.pic_0.next           1
tocollection                       1
reader_flag.paper1.next            1
chap1_finale                       1
tocloset                           1
tunic.capitol_0                    1
journals.pic_1.next                1
chap1_finale_c                     1
tocloset_dirty                     1
tunic.humanecology                 1
tunic.wildlife                     1
tocollectionflag                   1
reader.paper1.next                 1
intro                              1
Name: fqid, dtype: int64

In [15]:
sess1.text.value_counts()

undefined                                                          13
\u00f0\u0178\u02dc\u00b4                                            3
I need to get her free. She won't hold still!                       2
Maybe she'll let me take off the cup!                               2
Got one!                                                            2
                                                                   ..
Maybe I can help!                                                   1
Now I Just need to find all the cleaners from way back in 1916.     1
Thanks.                                                             1
Looks like a dry cleaning receipt.                                  1
I should go to the Capitol and tell Mrs. M!                         1
Name: text, Length: 344, dtype: int64

In [16]:
sess1.text_fqid.nunique()

76

In [17]:
sess1.text_fqid.value_counts()

tunic.wildlife.center.crane_ranger.crane                             30
tunic.historicalsociety.cage.confrontation                           21
tunic.historicalsociety.frontdesk.archivist.newspaper                18
tunic.historicalsociety.entry.groupconvo                             16
tunic.wildlife.center.wells.nodeer                                   16
tunic.historicalsociety.frontdesk.archivist.have_glass               15
tunic.historicalsociety.closet_dirty.gramps.news                     14
tunic.humanecology.frontdesk.worker.intro                            12
tunic.historicalsociety.basement.seescratches                        11
tunic.flaghouse.entry.flag_girl.hello                                10
tunic.historicalsociety.collection.cs                                 9
tunic.historicalsociety.collection.gramps.found                       9
tunic.drycleaner.frontdesk.worker.hub                                 9
tunic.historicalsociety.entry.groupconvo_flag                         9
tunic.historicalsociety.frontdesk.archivist_glasses.confrontation     9
tunic.library.frontdesk.worker.hello                                  8
tunic.historicalsociety.basement.ch3start                             8
tunic.historicalsociety.collection_flag.gramps.flag                   8
tunic.library.frontdesk.worker.wells                                  8
tunic.historicalsociety.basement.savedteddy                           8
tunic.library.frontdesk.worker.nelson                                 7
tunic.wildlife.center.expert.removed_cup                              6
tunic.library.frontdesk.worker.flag                                   6
tunic.historicalsociety.closet_dirty.what_happened                    5
tunic.historicalsociety.closet.gramps.intro_0_cs_0                    5
tunic.historicalsociety.frontdesk.archivist.hello                     5
tunic.historicalsociety.closet_dirty.trigger_scarf                    5
tunic.flaghouse.entry.flag_girl.symbol                                5
tunic.historicalsociety.entry.directory.closeup.archivist             4
tunic.historicalsociety.cage.glasses.afterteddy                       4
tunic.historicalsociety.cage.teddy.trapped                            4
tunic.historicalsociety.entry.boss.flag                               4
tunic.historicalsociety.closet.teddy.intro_0_cs_0                     4
tunic.historicalsociety.cage.unlockdoor                               3
tunic.historicalsociety.entry.wells.flag                              3
tunic.historicalsociety.stacks.journals.pic_2.bingo                   3
tunic.capitol_1.hall.boss.haveyougotit                                3
tunic.historicalsociety.stacks.journals_flag.pic_0.bingo              3
tunic.historicalsociety.closet.retirement_letter.hub                  3
tunic.drycleaner.frontdesk.worker.done                                3
tunic.humanecology.frontdesk.worker.badger                            3
tunic.historicalsociety.entry.boss.flag_recap                         2
tunic.historicalsociety.collection.tunic.slip                         2
tunic.wildlife.center.wells.animals2                                  2
tunic.library.microfiche.reader.paper2.bingo                          2
tunic.historicalsociety.basement.janitor                              2
tunic.kohlcenter.halloffame.plaque.face.date                          2
tunic.kohlcenter.halloffame.togrampa                                  2
tunic.capitol_0.hall.boss.talktogramps                                2
tunic.historicalsociety.closet_dirty.trigger_coffee                   2
tunic.historicalsociety.frontdesk.archivist.have_glass_recap          2
tunic.historicalsociety.closet.teddy.intro_0_cs_5                     2
tunic.historicalsociety.basement.gramps.whatdo                        2
tunic.drycleaner.frontdesk.logbook.page.bingo                         2
tunic.historicalsociety.entry.wells.talktogramps                      1
tunic.flaghouse.entry.flag_girl.symbol_recap                          1
tunic.historicalsociety.closet.notebook                               1
tunic.library.microfiche.reader_flag.paper2.bingo                     1
tunic.flaghouse.entry.colorbook                                       1
tunic.historicalsociety.closet.photo                                  1
tunic.historicalsociety.entry.boss.talktogramps                       1
tunic.wildlife.center.expert.recap                                    1
tunic.wildlife.center.tracks.hub.deer                                 1
tunic.library.frontdesk.wellsbadge.hub                                1
tunic.wildlife.center.remove_cup                                      1
tunic.wildlife.center.wells.animals                                   1
tunic.wildlife.center.coffee                                          1
tunic.historicalsociety.entry.wells.flag_recap                        1
tunic.historicalsociety.stacks.outtolunch                             1
tunic.historicalsociety.closet_dirty.gramps.helpclean                 1
tunic.historicalsociety.frontdesk.archivist.need_glass_0              1
tunic.historicalsociety.frontdesk.key                                 1
tunic.historicalsociety.frontdesk.magnify                             1
tunic.humanecology.frontdesk.businesscards.card_bingo.bingo           1
tunic.historicalsociety.cage.glasses.beforeteddy                      1
tunic.historicalsociety.closet.intro                                  1
Name: text_fqid, dtype: int64

In [18]:
sess1.room_fqid.value_counts()

tunic.historicalsociety.entry              123
tunic.wildlife.center                      104
tunic.historicalsociety.cage                83
tunic.historicalsociety.frontdesk           73
tunic.library.frontdesk                     58
tunic.historicalsociety.basement            53
tunic.historicalsociety.closet_dirty        50
tunic.historicalsociety.closet              47
tunic.humanecology.frontdesk                44
tunic.historicalsociety.stacks              42
tunic.drycleaner.frontdesk                  33
tunic.kohlcenter.halloffame                 33
tunic.flaghouse.entry                       32
tunic.historicalsociety.collection          30
tunic.library.microfiche                    28
tunic.capitol_1.hall                        23
tunic.historicalsociety.collection_flag     12
tunic.capitol_0.hall                        11
tunic.capitol_2.hall                         2
Name: room_fqid, dtype: int64

In [21]:
sess1_drop = sess1.drop(columns=['hover_duration'], axis=1)
sess1_drop.columns

Index(['session_id', 'index', 'elapsed_time', 'event_name', 'name', 'level',
       'room_coor_x', 'room_coor_y', 'screen_coor_x', 'screen_coor_y', 'text',
       'fqid', 'room_fqid', 'text_fqid', 'level_group'],
      dtype='object')

In [22]:
sess1_drop

,session_id,index,elapsed_time,event_name,name,level,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,text,fqid,room_fqid,text_fqid,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,-413.991405,-159.314686,380.0,494.0,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0-4
1,20090312431273200,1,1323,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
2,20090312431273200,2,831,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
3,20090312431273200,3,1147,person_click,basic,0,-413.991405,-159.314686,380.0,494.0,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
4,20090312431273200,4,1863,person_click,basic,0,-412.991405,-159.314686,381.0,494.0,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,20090312431273200,927,1267357,navigate_click,undefined,22,927.307255,-10.355929,838.0,335.0,NaN,tomap,tunic.historicalsociety.entry,NaN,13-22
877,20090312431273200,928,1268292,map_hover,basic,22,NaN,NaN,NaN,NaN,NaN,tomap,tunic.historicalsociety.entry,NaN,13-22
878,20090312431273200,929,1269474,map_click,undefined,22,457.523005,22.141338,443.0,316.0,NaN,tunic.capitol_2,tunic.historicalsociety.entry,NaN,13-22
879,20090312431273200,930,1270708,navigate_click,undefined,22,224.190321,-60.268671,404.0,337.0,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22
880,20090312431273200,931,1272679,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22

# Session #1 hover duration

In [23]:
sess1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 881 entries, 0 to 880
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      881 non-null    int64
 1   index           881 non-null    int64
 2   elapsed_time    881 non-null    int64
 3   event_name      881 non-null    object
 4   name            881 non-null    object
 5   level           881 non-null    int64
 6   room_coor_x     813 non-null    float64
 7   room_coor_y     813 non-null    float64
 8   screen_coor_x   813 non-null    float64
 9   screen_coor_y   813 non-null    float64
 10  hover_duration  65 non-null     float64
 11  text            384 non-null    object
 12  fqid            652 non-null    object
 13  room_fqid       881 non-null    object
 14  text_fqid       384 non-null    object
 15  level_group     881 non-null    object
dtypes: float64(5), int64(4), object(7)
memory usage: 117.0+ KB

In [24]:
sess1.hover_duration.describe()

count      65.000000
mean     1115.292308
std      1687.876733
min        15.000000
25%        67.000000
50%       318.000000
75%       983.000000
max      7899.000000
Name: hover_duration, dtype: float64

In [25]:
7899/1000 # 7 seconds is max hover duration

7.899

In [26]:
sess1['hover_duration']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
       ...
876      NaN
877    366.0
878      NaN
879      NaN
880      NaN
Name: hover_duration, Length: 881, dtype: float64

In [27]:
#sess1.hover_duration.value_counts()
import plotly.express as px

px.line(sess1, x=sess1.index, y='hover_duration')

In [29]:
sess1.room_coor_x.value_counts()

-413.991405    4
-181.522639    4
-175.946882    3
-412.991405    2
 630.690977    2
              ..
-228.142233    1
-232.141565    1
-234.141359    1
-234.141307    1
 224.190321    1
Name: room_coor_x, Length: 802, dtype: int64

# Process Train Data
- aggregate by session id and question groups

## what to do with columns with null values:  
- page - fill nan with -1
- room/screen coor - groupby question sections and mean?
- hover duration - groupby question sections and mean?
- text - leave nan or fill with -1 or something
- fqid - leave nan or fill with -1 or something
- text_fqid(detailed fqid) - leave nan or fill with -1 or something

In [34]:
sess1.event_name.unique()

array(['cutscene_click', 'person_click', 'navigate_click',
       'observation_click', 'notification_click', 'object_click',
       'object_hover', 'map_hover', 'map_click', 'checkpoint'],
      dtype=object)

In [50]:
len(sess1)

881

In [49]:
#len(sess1[sess1['level_group']=='0-4'])
sess1['level_group']=='0-4' # total data length and which one is 0-4

0       True
1       True
2       True
3       True
4       True
       ...
876    False
877    False
878    False
879    False
880    False
Name: level_group, Length: 881, dtype: bool

In [46]:
#len(sess1['level_group']=='0-4')
sess1[sess1['level_group']=='0-4']['event_name']
#sess1[sess1['level_group']=='0-4'].isna().sum()

0          cutscene_click
1            person_click
2            person_click
3            person_click
4            person_click
5            person_click
6            person_click
7            person_click
8            person_click
9            person_click
10         navigate_click
11           person_click
12         navigate_click
13      observation_click
14         navigate_click
15         navigate_click
16         navigate_click
17         navigate_click
18         navigate_click
19         navigate_click
20         navigate_click
21         navigate_click
22         navigate_click
23         navigate_click
24         navigate_click
25         navigate_click
26     notification_click
27           object_click
28         navigate_click
29     notification_click
30     notification_click
31     notification_click
32           object_click
33         navigate_click
34         navigate_click
35         navigate_click
36         navigate_click
37      observation_click
38         navigate_click
39         navigate_click
40         navigate_click
41         cutscene_click
42         cutscene_click
43         cutscene_click
44         cutscene_click
45         cutscene_click
46         cutscene_click
47         cutscene_click
48         cutscene_click
49           object_hover
50           object_click
51           object_click
52         cutscene_click
53         cutscene_click
54         cutscene_click
55         cutscene_click
56         cutscene_click
57         cutscene_click
58         cutscene_click
59         cutscene_click
60         navigate_click
61           person_click
62         navigate_click
63           person_click
64         navigate_click
65         navigate_click
66         navigate_click
67         navigate_click
68           object_click
69         navigate_click
70         navigate_click
71         navigate_click
72         cutscene_click
73         cutscene_click
74         cutscene_click
75         cutscene_click
76         cutscene_click
77         cutscene_click
78         cutscene_click
79         cutscene_click
80         cutscene_click
81         navigate_click
82           object_hover
83           object_click
84           object_click
85     notification_click
86     notification_click
87           object_hover
88           object_click
89         navigate_click
90           person_click
91           person_click
92           person_click
93           person_click
94           person_click
95           person_click
96           person_click
97           person_click
98           person_click
99         navigate_click
100        navigate_click
101        navigate_click
102        navigate_click
103        navigate_click
104        navigate_click
105        navigate_click
106        navigate_click
107        navigate_click
108     observation_click
109        navigate_click
110        navigate_click
111        navigate_click
112     observation_click
113        navigate_click
114        navigate_click
115        navigate_click
116        navigate_click
117        navigate_click
118        navigate_click
119        navigate_click
120          person_click
121        navigate_click
122        navigate_click
123        navigate_click
124        navigate_click
125        navigate_click
126        navigate_click
127             map_hover
128             map_hover
129             map_click
130        navigate_click
131        navigate_click
132        navigate_click
133        navigate_click
134        navigate_click
135        navigate_click
136        navigate_click
137        navigate_click
138        navigate_click
139        navigate_click
140        navigate_click
141        navigate_click
142        navigate_click
143        navigate_click
144          object_click
145    notification_click
146    notification_click
147          object_click
148          object_hover
149          object_click
150        cutscene_click
151        cutscene_click
152        navigate_click
153        navigate_click
154        navigate_click
155        navigate_click
156        navigate_click
157        navigate_click
158        navigate_click
159        navigate_click
160             map_hover
161             map_hover
162             map_click
163        navigate_click
164            checkpoint
Name: event_name, dtype: object

In [37]:
sess1.groupby(['session_id', 'level_group']).agg({'event_name' : 'count'})

                               event_name
session_id        level_group
20090312431273200 0-4                 165
                  13-22               420
                  5-12                296

In [51]:
sess1.name.unique()

array(['basic', 'undefined', 'close'], dtype=object)

In [52]:
sess1.name.value_counts()

basic        463
undefined    401
close         17
Name: name, dtype: int64

In [53]:
sess1.level.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22], dtype=int64)

In [56]:
sess1.room_coor_x.nunique()

802

In [57]:
sess1.groupby(['session_id', 'level_group']).agg({'room_coor_x':'nunique'})

                               room_coor_x
session_id        level_group
20090312431273200 0-4                  152
                  13-22                385
                  5-12                 265

In [58]:
sess1.groupby(['session_id', 'level_group']).agg({'hover_duration':'sum'})

                               hover_duration
session_id        level_group
20090312431273200 0-4                 19116.0
                  13-22               24298.0
                  5-12                29080.0

In [59]:
#text, 344 uniques
print('unique:', sess1.text.unique())
print('nunique:', sess1.text.nunique())

unique: ['undefined' 'Whatcha doing over there, Jo?' 'Just talking to Teddy.'
 'I gotta run to my meeting!' 'Can I come, Gramps?'
 'Sure thing, Jo. Grab your notebook and come upstairs!'
 'See you later, Teddy.' "I get to go to Gramps's meeting!"
 'Now where did I put my notebook?' '\\u00f0\\u0178\\u02dc\\u00b4' nan
 'I love these photos of me and Teddy!' 'Found it!'
 'Gramps is in trouble for losing papers?' "This can't be right!"
 'Gramps is a great historian!' "Hmm. Button's still not working."
 "Let's get started. The Wisconsin Wonders exhibit opens tomorrow!"
 'Who wants to investigate the shirt artifact?'
 "Not Leopold here. He's been losing papers lately." 'Hey!'
 "It's true, they do keep going missing lately." 'See?'
 'Besides, I already figured out the shirt.'
 "It's a women's basketball jersey!" 'That settles it.'
 'Wells, finish up your report.'
 "Leopold, why don't you help me set up in the Capitol?"
 'We need to talk about that missing paperwork.' 'Will do, Boss.'
 "Hey Jo, let's take a look at the shirt!"
 'Your grampa is waiting for you in the collection room.'
 "Why don't you go catch up with your grampa?"
 'What a fascinating artifact!' "Wow, that's so cool, Gramps!"
 'Can I take a closer look?' "Hmmm. Shouldn't you be doing your homework?"
 "It's already all done!"
 'Plus, my teacher said I could help you out for extra credit!'
 "Well, that's good enough for me." 'Go ahead, take a peek at the shirt!'
 'This looks like a clue!' "I'll record this in my notebook."
 'Find anything?' 'Yes! This old slip from 1916.' 'I knew it!'
 "I'm not so sure that this is a basketball jersey."
 'Wait, you mean Wells is wrong?!' 'Could be. But we need evidence!'
 "Why don't you head to the Basketball Center and rustle up some clues?"
 'Sure!' "I'll be at the Capitol. Let me know if you find anything!"
 'Better check back later.' "That's it!"
 "The slip is from 1916 but the team didn't start until 1974!"
 'Our shirt is too old to be a basketball jersey!'
 'I need to get to the Capitol and tell Gramps!'
 'What are you still doing here,  Jolie?'
 'Go find your grampa and get to work!' 'Oh no!' 'What happened here?!'
 "I don't know!" 'I got here and the whole place was a mess!'
 'Can you help me tidy up?' "Teddy's scarf! Somebody must've taken him!"
 'Try not to panic, Jo.' 'Maybe he just got scared and ran off.'
 'But he never goes anywhere without his scarf!'
 "I think he's in trouble!" 'Is this your coffee, Gramps?'
 "Nope, that's from Bean Town. I only drink Holdgers!"
 "Who could've done this?" "It must've been Wells."
 "He's always trying to get you in trouble, and he doesn't like animals!"
 'Slow down, Jo.' 'But what if Wells kidnapped Teddy?'
 'Then we need evidence.' "You're right, Gramps. Let's investigate!"
 "I'm afraid my papers have gone missing in this mess."
 "You'll have to get started without me." "Okay. I'll find Teddy!"
 "And I'll figure out the shirt, too." 'I knew I could count on you, Jo!'
 "Why don't you go upstairs and see the archivist?"
 "He's our expert record keeper." 'I need your help!' 'Who are you?'
 "I'm Leopold's grandkid!" "Sorry, I'm too busy for kids right now."
 'Now if only I could read this thing.'
 "Can't believe I lost my reading glasses."
 'I bet the archivist could use this!' "Ah, that's better!"
 'Did you have a question?' 'Yes! I was wondering-' 'Wait a minute!'
 'Where did you get that coffee?' "Oh, that's from Bean Town."
 'I ran into Wells there this morning.' 'Wells? I knew it!'
 'Do you know anything about this slip?' 'I found it on an old shirt.'
 'An old shirt? Try the university.'
 'You can talk to a textile expert there.' "What's a textile expert?"
 'They study clothes and fabric.' 'Great! Thanks for the help!'
 'Head over to the university.' 'Hello there!'
 'Wow! What is all this stuff?' "It's our Norwegian Craft exhibit!"
 'Can I give you the tour?' "Sorry, I'm in a hurry."
 'Do you know what this slip is?' 'Looks like a dry cleaning receipt.'
 'Thanks.'
 'Now I Just need to find all the cleaners from way back in 1916.'
 'Maybe I can help!'
 "I've got a stack of business cards from my favorite cleaners."
 "Why don't you take a look?"
 'This place was around in 1916! I can start there!'
 "You haven't seen any badgers around here, have you?" 'Badgers? No.'
 'Okay. Thanks anyway.' 'Hi! How can I help you?'
 'I need to find the owner of this slip.'
 "Well, I can't show our log books to just anybody." 'Please?'
 "It's for Grampa Leo. He's a historian!" 'Leo... you mean Leopold?'
 'Your gramps is awesome! Always full of stories.'
 "Guess it couldn't hurt to let you take a look." "Here's the log book."
 "It's a match!" 'Theodora Youmans must be the owner!'
 'Do you know who Theodora Youmans is?'
 "Hmmm... not sure. Why don't you try the library?" 'Thanks for the help!'
 'Oh, hello there!' 'How can I help you?'
 'Have you seen a badger around here?' "I'm afraid not."
 'Please let me know if you do.'
 "I'm also looking for Theodora Youmans. Have you heard of her?"
 'Theodora Youmans? Of course!'
 "Check out our microfiche. It's right through that door."
 'Youmans was a suffragist!' 'She helped get votes for women!'
 'Wells! What was he doing here? I should ask the librarian.'
 'What was Wells doing here?' 'He was looking for a taxidermist.'
 "What's a taxidermist?" 'Not sure. Here, let me look it up.'
 '\\Taxidermy: the art of preparing, stuffing, and mounting the skins of animals.\\'
 'Oh no... Teddy!' 'Can you help me find Wells?'
 'You could ask the archivist. He knows everybody!'
 "Jolie! I was hoping you'd stop by. Any news on the shirt artifact?"
 "I haven't quite figured it out just yet..."
 "Well, get on it. I'm counting on you and your gramps to figure this out!"
 'Can you help me? I need to find Wells!' "I haven't seen him."
 'Please? This is really important.' "Sorry, can't help you."
 'Do you have any info on Theodora Youmans?'
 'Theodora Youmans? Is that who owned the shirt?' 'Yep.'
 "Why didn't you say so?" 'Youmans was a suffragist here in Wisconsin.'
 'She led marches and helped women get the right to vote!'
 "Wait a sec. Women couldn't vote?!"
 'Nope. But Youmans and other suffragists worked hard to change that.'
 'Thanks to them, Wisconsin was the first state to approve votes for women!'
 'Wow!' "Here's a call number to find more info in the Stacks."
 'Where are the Stacks?' 'Right outside the door.' 'Hey, this is Youmans!'
 "And look! She's wearing the shirt!"
 'I should go to the Capitol and tell everyone!' 'Jo!'
 'Check out the next artifact!' 'What is it?'
 "I think it's a flag! Pretty interesting, huh?"
 "It's really cool, Gramps. But I'm worried about Teddy."
 "He's still missing!" "We'll find him, Jo."
 'Want to look for more clues?' "We'll find Teddy."
 'We just have to keep our eyes open!' 'Hey, look at those scratches!'
 'The kidnapper probably took Teddy on the elevator!' "You're right, Jo!"
 "Why isn't the button working?" "We'll need a key card."
 'I had one, but Teddy chewed it up.' "I've got Wells's ID!"
 'What should we do next?'
 "I need to take the artifact upstairs. Why don't you investigate those scratch marks?"
 "Okay. I'll try." 'Teddy, here I come!'
 'I wonder whose glasses these are.' 'Teddy!!!'
 "Hang on. I'll get you out of there!"
 'Whoever lost these glasses probably took Teddy!'
 'How can I find out whose glasses these are?'
 'Oh! There was a staff directory in the entryway!'
 "I'll go look at everyone's pictures!" 'Those are the same glasses!'
 "The archivist must've taken Teddy!"
 "Yes! It's the key for Teddy's cage!" 'I found the key!'
 "Come on, let's get out of here!" "Here's your scarf back!"
 'What are you doing down here?' 'And how did that badger get free?'
 "I'm here to rescue my friend!" "What's going on here?"
 'Thanks for coming, Boss.' 'I told you!'
 'I captured a badger in our museum!'
 "He's been eating my lunch every day this week!" 'He has??'
 "I've seen him eating homework and important papers, too."
 "Jolie- keep your badger under control, or he'll have to go."
 'And you, Frank-' "You can't just steal Jolie's pet." 'Ugh. Fine.'
 'Alright, Jolie. Back to work.' "Come on, Teddy. Let's go help Gramps!"
 "Let's go help Gramps!" 'Gramps must be up in the collection room.'
 "Let's go find him!" "Teddy! I'm glad to see you."
 'The archivist had him locked up!' 'Poor badger.'
 "You're becoming quite the detective, Jo."
 'Notice any clues about this flag?' 'Well... it looks hand-stitched.'
 'Good catch!' 'Go on, tell the boss what you found!'
 "I'm telling you, Boss. Taxidermy is the way to go!"
 'Nonsense. I want live animals at the exhibit, not stuffed ones.'
 "Ah, Jolie! I'm glad you're here."
 "I'm putting you in charge of the flag case."
 'Make sure to get some old photos for the exhibit, like last time!'
 "Wait! Can't I do it?"
 'The symbol on the flag looks sort of like a deer hoof.'
 'It could be an early design for the Wisconsin state flag!'
 'Wells, you already have a job to do.' 'What now, kid?'
 'Do you really think that symbol is a deer hoof?' 'Not sure.'
 'Do you know where I can find a deer expert?'
 'Hmm. You could try the Aldo Leopold Wildlife Center.'
 'I have to head over there and check out the animals.'
 "I'll ride with you!" "Come on, kid. Let's go."
 'Head over to the Wildlife Center!' "I'm sure they'll be able to help."
 'People sure drink a lot of coffee around here.' "I can't believe this."
 'Ugh...' 'Oh no! What happened to that crane?'
 'Her beak is stuck in a coffee cup.' "It's lucky we found her."
 'Ugh! Those cups are all over the place.'
 "I need to get her free. She won't hold still!" 'Can Teddy and I help?'
 'Sure! Give it a try.' 'Careful. That beak is sharp!'
 'We need to calm her down, Teddy.' 'Any ideas?'
 '\\u00f0\\u0178\\u00a6\\u2014' 'Oh yeah, cranes eat insects!'
 'Luckily there are tons of insects around here...' 'Got one!'
 "Maybe she'll let me take off the cup!"
 "It's OK, girl! Look, I found you a cricket!" 'You did it! Thanks, kid.'
 'Can I help you with anything?' "I'm investigating this symbol."
 'Does it look like a deer hoof?'
 "There's a diagram of animal tracks over there." 'Go take a look!'
 "That hoofprint doesn't match the flag!" 'Thanks for your help, kid!'
 "So? What'd you find out?" "Looks like it's not a deer hoof."
 "Oh no. If I don't impress the boss soon,  I'm gonna get fired!"
 'Hey, Wells...' 'I think I might be able to help you.'
 "No thanks. I don't need help from kids."
 'Are you sure? I know where you can find a real, live badger for the exhibit!'
 'Wait! What?! Really?' 'Wells, meet Teddy.'
 '\\u00f0\\u0178\\u02dc\\u0160' "He says he'd be willing to help out."
 'Yes!!!'
 'We still need to figure out that flag. Do you know anyone who could help?'
 "Hmm. Let's see..."
 'Actually, I went to school with somebody who LOVES old flags.'
 "Why don't you go talk to her? I'll let her know you're coming."
 'Hey, nice dog! What breed is he?' "Actually, he's a badger."
 "Oh, cool! I've never seen a badger in real life."
 "You've got a million flags here!" "Yep. I'm a vexillophile!"
 "What's a vexillophile? " 'It just means flag expert. How can I help?'
 "I'm investigating this flag." 'Can you take a look?'
 "Hey, I've seen that symbol before! Check it out!"
 '\\Ecology flag, by Ron Cobb.\\' "It's an ecology flag!"
 'Do you know what this flag was used for?' "I'm not sure."
 "If I were you, I'd go to the library and do some digging."
 'Good idea. Thanks!' 'Welcome back, Dear! How can I help you?'
 'I need to learn more about this flag!'
 'It has something to do with ecology.'
 'Hmm... those stripes remind me of the American flag.'
 'Your flag must have been part of a national movement!'
 "Go check the microfiche. Maybe you'll find something!"
 "Hey! That's Governor Nelson in front of our flag!"
 'I found the flag! Governor Nelson used it on the first Earth Day!'
 'Wow! You figured it out!'
 'Now I just need some old photos, like last time.'
 'The boss is gonna love it!' 'You could try the archives.'
 'Though the archivist might be too busy to help...' 'Okay. Thanks!'
 'What are you doing here?' "We're looking for some photos."
 "It's for the flag display!" 'Wait a minute...'
 "YOU'RE the new history detective everybody's talking about?"
 "Teddy's helping too." 'What kind of photos do you need?'
 'Something to do with ecology and Wisconsin.'
 "Here's a call number for the Stacks. Go find some photos."
 'Look at all those activists!' 'This is perfect for the exhibit.'
 'I should go to the Capitol and tell Mrs. M!']
nunique: 344

In [63]:
sess1.text.value_counts()

undefined                                                          13
\u00f0\u0178\u02dc\u00b4                                            3
I need to get her free. She won't hold still!                       2
Maybe she'll let me take off the cup!                               2
Got one!                                                            2
                                                                   ..
Maybe I can help!                                                   1
Now I Just need to find all the cleaners from way back in 1916.     1
Thanks.                                                             1
Looks like a dry cleaning receipt.                                  1
I should go to the Capitol and tell Mrs. M!                         1
Name: text, Length: 344, dtype: int64

In [65]:
#fqid, 95 uniques
print('unique:', sess1.fqid.unique())
print('nunique:', sess1.fqid.nunique())
print(sess1.fqid.value_counts())

unique: ['intro' 'gramps' 'teddy' 'photo' nan 'notebook' 'retirement_letter'
 'tobasement' 'janitor' 'toentry' 'groupconvo' 'report' 'boss' 'wells'
 'directory' 'tocollection' 'cs' 'tunic' 'tunic.hub.slip' 'tostacks'
 'outtolunch' 'tocloset' 'tomap' 'tunic.historicalsociety'
 'tunic.kohlcenter' 'plaque' 'plaque.face.date' 'togrampa'
 'tunic.capitol_0' 'chap1_finale' 'chap1_finale_c' 'tocloset_dirty'
 'what_happened' 'trigger_scarf' 'trigger_coffee' 'tunic.capitol_1'
 'tofrontdesk' 'archivist' 'magnify' 'tunic.humanecology' 'worker'
 'businesscards' 'businesscards.card_0.next' 'businesscards.card_1.next'
 'businesscards.card_bingo.next' 'businesscards.card_bingo.bingo'
 'tohallway' 'tunic.drycleaner' 'logbook' 'logbook.page.bingo'
 'tunic.library' 'tomicrofiche' 'reader' 'reader.paper0.next'
 'reader.paper1.next' 'reader.paper2.bingo' 'wellsbadge' 'journals'
 'journals.hub.topics' 'journals.pic_0.next' 'journals.pic_1.next'
 'journals.pic_2.bingo' 'chap2_finale_c' 'ch3start' 'seescratches'
 'tocage' 'glasses' 'directory.closeup.archivist' 'key' 'unlockdoor'
 'confrontation' 'savedteddy' 'tocollectionflag' 'groupconvo_flag'
 'tunic.capitol_2' 'tunic.wildlife' 'coffee' 'crane_ranger' 'remove_cup'
 'expert' 'tracks' 'tracks.hub.deer' 'tunic.flaghouse' 'flag_girl'
 'colorbook' 'reader_flag' 'reader_flag.paper0.next'
 'reader_flag.paper1.next' 'reader_flag.paper2.bingo' 'archivist_glasses'
 'journals_flag' 'journals_flag.hub.topics_old' 'journals_flag.hub.topics'
 'journals_flag.pic_0.bingo' 'journals_flag.pic_0.next' 'chap4_finale_c']
nunique: 95
worker                            64
archivist                         46
gramps                            44
crane_ranger                      32
wells                             32
toentry                           23
confrontation                     22
flag_girl                         20
groupconvo                        18
boss                              17
tomap                             16
teddy                             14
seescratches                      13
tobasement                        11
groupconvo_flag                   11
archivist_glasses                 10
tostacks                          10
expert                             9
cs                                 9
savedteddy                         8
ch3start                           8
tunic.capitol_1                    7
logbook                            7
tunic.historicalsociety            7
glasses                            7
trigger_scarf                      6
tofrontdesk                        6
tunic.drycleaner                   6
businesscards                      5
tunic.library                      5
reader                             5
journals                           5
what_happened                      5
directory                          5
colorbook                          5
reader_flag                        5
tracks                             4
journals.hub.topics                4
directory.closeup.archivist        4
businesscards.card_0.next          4
tunic.capitol_2                    4
janitor                            4
tunic                              4
unlockdoor                         4
logbook.page.bingo                 4
trigger_coffee                     3
journals_flag.pic_0.bingo          3
journals.pic_0.next                3
reader.paper0.next                 3
chap2_finale_c                     3
tunic.kohlcenter                   3
plaque                             3
tracks.hub.deer                    3
remove_cup                         2
reader_flag.paper0.next            2
key                                2
journals_flag                      2
journals_flag.hub.topics           2
coffee                             2
tunic.flaghouse                    2
tocage                             2
reader_flag.paper2.bingo           2
chap4_finale_c                     2
journals.pic_2.bingo               2
businesscards.card_bingo.next      2
plaque.face.date                   2
togrampa                           2
report                             2
retirement_letter                  2
magnify                            2
notebook                           2
outtolunch                         2
businesscards.card_1.next          2
photo                              2
businesscards.card_bingo.bingo     2
tohallway                          2
tomicrofiche                       2
reader.paper2.bingo                2
wellsbadge                         2
tunic.hub.slip                     2
journals_flag.hub.topics_old       1
journals_flag.pic_0.next           1
tocollection                       1
reader_flag.paper1.next            1
chap1_finale                       1
tocloset                           1
tunic.capitol_0                    1
journals.pic_1.next                1
chap1_finale_c                     1
tocloset_dirty                     1
tunic.humanecology                 1
tunic.wildlife                     1
tocollectionflag                   1
reader.paper1.next                 1
intro                              1
Name: fqid, dtype: int64

In [66]:
#room_fqid, 19 uniques
print('unique:', sess1.room_fqid.unique())
print('nunique:', sess1.room_fqid.nunique())
print(sess1.room_fqid.value_counts())

unique: ['tunic.historicalsociety.closet' 'tunic.historicalsociety.basement'
 'tunic.historicalsociety.entry' 'tunic.historicalsociety.collection'
 'tunic.historicalsociety.stacks' 'tunic.kohlcenter.halloffame'
 'tunic.capitol_0.hall' 'tunic.historicalsociety.closet_dirty'
 'tunic.historicalsociety.frontdesk' 'tunic.humanecology.frontdesk'
 'tunic.drycleaner.frontdesk' 'tunic.library.frontdesk'
 'tunic.library.microfiche' 'tunic.capitol_1.hall'
 'tunic.historicalsociety.cage' 'tunic.historicalsociety.collection_flag'
 'tunic.wildlife.center' 'tunic.flaghouse.entry' 'tunic.capitol_2.hall']
nunique: 19
tunic.historicalsociety.entry              123
tunic.wildlife.center                      104
tunic.historicalsociety.cage                83
tunic.historicalsociety.frontdesk           73
tunic.library.frontdesk                     58
tunic.historicalsociety.basement            53
tunic.historicalsociety.closet_dirty        50
tunic.historicalsociety.closet              47
tunic.humanecology.frontdesk                44
tunic.historicalsociety.stacks              42
tunic.drycleaner.frontdesk                  33
tunic.kohlcenter.halloffame                 33
tunic.flaghouse.entry                       32
tunic.historicalsociety.collection          30
tunic.library.microfiche                    28
tunic.capitol_1.hall                        23
tunic.historicalsociety.collection_flag     12
tunic.capitol_0.hall                        11
tunic.capitol_2.hall                         2
Name: room_fqid, dtype: int64

In [68]:
#text_fqid, 76 uniques
#print('unique:', sess1.text_fqid.unique())
print('nunique:', sess1.text_fqid.nunique())
#print(sess1.text_fqid.value_counts())

nunique: 76

In [32]:
# dropped 'fullscreen', 'hq', 'music', 'page'
train.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26296946 entries, 0 to 26296945
Data columns (total 16 columns):
 #   Column          Non-Null Count     Dtype
---  ------          --------------     -----
 0   session_id      26296946 non-null  int64
 1   index           26296946 non-null  int64
 2   elapsed_time    26296946 non-null  int64
 3   event_name      26296946 non-null  object
 4   name            26296946 non-null  object
 5   level           26296946 non-null  int64
 6   room_coor_x     24223674 non-null  float64
 7   room_coor_y     24223674 non-null  float64
 8   screen_coor_x   24223674 non-null  float64
 9   screen_coor_y   24223674 non-null  float64
 10  hover_duration  2002244 non-null   float64
 11  text            9617139 non-null   object
 12  fqid            18022531 non-null  object
 13  room_fqid       26296946 non-null  object
 14  text_fqid       9617244 non-null   object
 15  level_group     26296946 non-null  object
dtypes: float64(5), int64(4), object(7)
memory usage: 3.1+ GB

In [69]:
# not included: name, 
train_agg = train.groupby(['session_id', 'level_group']).agg({
    'index':'max',
    'elapsed_time':'max',
    'event_name' : 'count',
    'level':'mean',
    'room_coor_x':'nunique',
    'room_coor_y':'nunique',
    'screen_coor_x':'nunique',
    'screen_coor_y':'nunique',
    'hover_duration':'sum',
    'text':'nunique',
    'fqid':'nunique',
    'room_fqid':'nunique',
    'text_fqid':'nunique'
    }
)
train_agg

                               index  elapsed_time  event_name      level  \
session_id        level_group
20090312431273200 0-4            164        194860         165   1.945455
                  13-22          931       1272679         420  17.402381
                  5-12           470        499235         296   8.054054
20090312433251036 0-4            138        233752         139   1.870504
                  13-22         1875       3815334        1297  17.762529
...                              ...           ...         ...        ...
22100219442786200 13-22          920       1218877         423  17.671395
                  5-12           453        561672         278   8.111511
22100221145014656 0-4            210        435055         211   2.061611
                  13-22         1604       5487952         760  18.127632
                  5-12           799       3668994         576   8.338542

                               room_coor_x  room_coor_y  screen_coor_x  \
session_id        level_group
20090312431273200 0-4                  152          145            127
                  13-22                385          381            249
                  5-12                 265          210            185
20090312433251036 0-4                  116          108             70
                  13-22               1012          955            512
...                                    ...          ...            ...
22100219442786200 13-22                379          365            179
                  5-12                 236          169            104
22100221145014656 0-4                  194          189            165
                  13-22                654          644            414
                  5-12                 483          428            336

                               screen_coor_y  hover_duration  text  fqid  \
session_id        level_group
20090312431273200 0-4                    108         19116.0    56    30
                  13-22                  221         24298.0   168    49
                  5-12                   159         29080.0   124    39
20090312433251036 0-4                     66         11030.0    49    22
                  13-22                  406        181537.0   183    73
...                                      ...             ...   ...   ...
22100219442786200 13-22                  160         26652.0   166    49
                  5-12                    98         37191.0   116    41
22100221145014656 0-4                    149         45811.0    64    27
                  13-22                  333         56865.0   205    54
                  5-12                   299        115981.0   145    47

                               room_fqid  text_fqid
session_id        level_group
20090312431273200 0-4                  7         17
                  13-22               12         35
                  5-12                11         24
20090312433251036 0-4                  6         11
                  13-22               16         43
...                                  ...        ...
22100219442786200 13-22               12         33
                  5-12                11         20
22100221145014656 0-4                  7         17
                  13-22               13         36
                  5-12                12         26

[70686 rows x 13 columns]

In [71]:
# explode indexes
train_agg_idx = train_agg.reset_index()
train_agg_idx

,session_id,level_group,index,elapsed_time,event_name,level,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid
0,20090312431273200,0-4,164,194860,165,1.945455,152,145,127,108,19116.0,56,30,7,17
1,20090312431273200,13-22,931,1272679,420,17.402381,385,381,249,221,24298.0,168,49,12,35
2,20090312431273200,5-12,470,499235,296,8.054054,265,210,185,159,29080.0,124,39,11,24
3,20090312433251036,0-4,138,233752,139,1.870504,116,108,70,66,11030.0,49,22,6,11
4,20090312433251036,13-22,1875,3815334,1297,17.762529,1012,955,512,406,181537.0,183,73,16,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70681,22100219442786200,13-22,920,1218877,423,17.671395,379,365,179,160,26652.0,166,49,12,33
70682,22100219442786200,5-12,453,561672,278,8.111511,236,169,104,98,37191.0,116,41,11,20
70683,22100221145014656,0-4,210,435055,211,2.061611,194,189,165,149,45811.0,64,27,7,17
70684,22100221145014656,13-22,1604,5487952,760,18.127632,654,644,414,333,56865.0,205,54,13,36
70685,22100221145014656,5-12,799,3668994,576,8.338542,483,428,336,299,115981.0,145,47,12,26

# fix train labels

In [72]:
train_labels

                   session_id  correct
0        20090312431273200_q1        1
1        20090312433251036_q1        0
2        20090312455206810_q1        1
3        20090313091715820_q1        0
4        20090313571836404_q1        1
...                       ...      ...
424111  22100215342220508_q18        1
424112  22100215460321130_q18        1
424113  22100217104993650_q18        1
424114  22100219442786200_q18        1
424115  22100221145014656_q18        1

[424116 rows x 2 columns]

In [73]:
train_labels_split

                   session_id                 id  question  correct
0        20090312431273200_q1  20090312431273200         1        1
1        20090312431273200_q2  20090312431273200         2        1
2        20090312431273200_q3  20090312431273200         3        1
3        20090312431273200_q4  20090312431273200         4        1
4        20090312431273200_q5  20090312431273200         5        1
...                       ...                ...       ...      ...
424111  22100221145014656_q14  22100221145014656        14        0
424112  22100221145014656_q15  22100221145014656        15        0
424113  22100221145014656_q16  22100221145014656        16        0
424114  22100221145014656_q17  22100221145014656        17        1
424115  22100221145014656_q18  22100221145014656        18        1

[424116 rows x 4 columns]

In [83]:
# # add columns for question level groups so i can join with train set
# train_labels_split['level_group'] = np.where(train_labels_split['question']<=4, '0-4')
# train_labels_split['level_group'] = np.where((train_labels_split['question']>4) & (train_labels_split['question']<=12), '5-12')
# train_labels_split['level_group'] = np.where((train_labels_split['question']>12) & (train_labels_split['question']<=22), '13-22')

train_labels_split.loc[train_labels_split['question']<=4, 'level_group'] ='0-4'
train_labels_split.loc[(train_labels_split['question']>4) & (train_labels_split['question']<=12), 'level_group'] ='5-12'
train_labels_split.loc[(train_labels_split['question']>12) & (train_labels_split['question']<=22), 'level_group'] ='13-22'

In [90]:
#train_labels_split.drop('session_id', axis=1, inplace=True)
train_labels_split.rename(columns={'id':'session_id'}, inplace=True)
train_labels_split

               session_id  question  correct level_group
0       20090312431273200         1        1         0-4
1       20090312431273200         2        1         0-4
2       20090312431273200         3        1         0-4
3       20090312431273200         4        1         0-4
4       20090312431273200         5        1        5-12
...                   ...       ...      ...         ...
424111  22100221145014656        14        0       13-22
424112  22100221145014656        15        0       13-22
424113  22100221145014656        16        0       13-22
424114  22100221145014656        17        1       13-22
424115  22100221145014656        18        1       13-22

[424116 rows x 4 columns]

# join train and train_labels
- Need to create multi label target column for each session id's level groups
- search xgboost multiclass classification

In [91]:
train_agg_idx.join(train_labels_split, on=['session_id', 'level_group'], how='left')

ValueError: len(left_on) must equal the number of levels in the index of "right"